import SearchInput from './components/SearchInput'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col gap-10 items-center p-6">
          <SearchInput />
          <div className="flex flex-col items-center w-full">{children}</div>
       

        </div>

        </body>
    </html>
  )
}
